blank_issues_enabled: true
contact_links:
  - name: Upstream Apache Ossie
    url: https://github.com/apache/ossie
    about: File issues about the Apache Ossie specification itself (not this KCL library) here.
  - name: Enkinex
    url: https://enkinex.org
    about: General questions about Enkinex and its projects.
